### ISSUE TITLE
EventBus post 流程图 是不是有点小问题？

### ISSUE THREAD

**Issue by zondaOf2012** [android-cn/android-open-project-analysis#19]
[post 流程图](https://github.com/android-cn/android-open-project-analysis/blob/master/event-bus/image/post-flow-chart.png)

“事件是否正在分发” 然后 N 和 Y 写反了？ @Trinea

**Comment by Trinea** [comment]
确实是，感谢提醒，已修正（浏览器可能有缓存）

其他问题欢迎反馈
