### ISSUE TITLE
Dagger分析里面的运行时流程图是否有点问题？

### ISSUE THREAD

**Issue by Piasy** [android-cn/android-open-project-analysis#30]
![image](https://cloud.githubusercontent.com/assets/3098704/6866326/001aa488-d4b2-11e4-8e29-577b2c5354b4.png)
第二个判断，“是”分支才需要“载入这些依赖的Binding”吧？

**Comment by Trinea** [comment]
@Piasy 多谢指正，我们会在下期将这些问题一起修改发布在 www.codekk.com

**Comment by rengwuxian** [comment]
Hi @Piasy ，

刚才和 @Trinea 沟通了一下，是这样的：

你仔细看一下，第二个判断其实是一个 while 循环，意思是“如果引入的依赖对象其内部带来了新的依赖，需要把新的依赖载入”。因此这里确实应该是“否”，即“还有未载入的新的依赖”。

不过我承认这个图画得不够清晰，导致你看错。谢谢你的阅读哈！

**Comment by Piasy** [comment]
了解了。
