### ISSUE TITLE
公共技术点之 Java 反射 Reflection，内容有误。

### ISSUE THREAD

**Issue by xiaoniao** [android-cn/android-open-project-analysis#36]
4 反射获取类中的字段 中
这里需要注意的是 getDeclaredMethod 和 getDeclaredMethods 包含 private、protected、default、public 的函数,并且通过这两个函数获取到的只是在自身中定义的函数,从父类中集成的函数不能够获取到。而 getMethod 和 getMethods 只包含 public 函数,父类中的公有函数也能够获取到。

应该为getDeclaredField  、getDeclaredFields 、getField 、getFields。

**Comment by dxjia** [comment]
field是获取成员变量吧

**Comment by Trinea** [comment]
感谢反馈，这篇文章还没完全审核结束，晚点我看下。另外有问题也可以直接提交 PR

**Comment by Trinea** [comment]
已修改
