### ISSUE TITLE
能不能加个Retrofit的分析呢

### ISSUE THREAD

**Issue by tedzyc** [android-cn/android-open-project-analysis#53]
retrofit这个轮子好，自带okHttp，结合RxAndroid，更加地好，不知何时那个大神来个深入分析
我看了一些评论：http://www.truiton.com/2015/04/android-volley-vs-retrofit-better-approach/
这里volley都给分析过了，非常期待对retrofit的分析（它的优缺点都希望看到）

**Comment by Trinea** [comment]
会有的，就是要稍微等一段时间

**Comment by Kevin1466** [comment]
我想做Retrofit的分析。
